name: Bing Rewards Daily
on:
  schedule:
    - cron: '0 12 * * *'   # runs daily at 12:00 PM UTC (5:30 PM IST)
  workflow_dispatch:

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install playwright faker
          playwright install chromium --with-deps
      - name: Run Script
        run: |
          python bing_search_24gv.py
          python bing_search_vizz.py
